defaultPulsarImageTag: 3.1.0

volumes:
  persistence: false

affinity:
  anti_affinity: false

components:
  autorecovery: false
  pulsar_manager: true
  functions: true

zookeeper:
  replicaCount: 1

bookkeeper:
  replicaCount: 1

broker:
  replicaCount: 1
  configData:
    autoSkipNonRecoverableData: "true"
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"

initialize: true

images:
  pulsar_manager:
    tag: v0.4.0

proxy:
  replicaCount: 1

kube-prometheus-stack:
  enabled: false
  prometheusOperator:
    enabled: false
  grafana:
    enabled: false
  alertmanager:
    enabled: false
  prometheus:
    enabled: false
